### ISSUE TITLE
DNS entry removal error

### ISSUE THREAD

**Issue by PixelRobots** [az-acme/az-acme-cli#16]
Seems that the DNS _acme-challenge. entry gets removed after the certificate has been created. it then goes to clean it up and cant find it.

![image](https://user-images.githubusercontent.com/22979170/178748908-2c34d687-a9c7-43d9-a49e-a290e5c54497.png)

**Comment by ross-mcdermott** [comment]
@PixelRobots could you provide the DNS you were trying to configure (or representative version if you can't share). Specifically was it subject only or subject plus san?

**Comment by ross-mcdermott** [comment]
Accidental close!

**Comment by PixelRobots** [comment]
Both times it was with San. I tried with a wildcard and also with a domain name. So:

*.az.pixelrobots.co.uk
1.az.pixelrobots.co.uk

Hope that helps.

**Comment by ross-mcdermott** [comment]
@PixelRobots could you take a look at https://github.com/az-acme/az-acme-cli/releases/tag/v0.3 and confirm it resolves the issue please?
