### ISSUE TITLE
 urn:ietf:params:acme:error:malformed: Unable to update challenge :: authorization must be pending

### ISSUE THREAD

**Issue by bjburke002** [az-acme/az-acme-cli#28]
```
`{
  "type": "dns-01",
  "status": "invalid",
  "error": {
    "type": "urn:ietf:params:acme:error:dns",
    "detail": "DNS problem: NXDOMAIN looking up TXT for <domain> - check that a DNS record exists for this domain",
    "status": 400
  },
  "url": "<url>",
  "token": "<token>",
  "validated": "2022-11-17T17:20:15Z"
}`
```

I've noticed this behavior on new orders for the last few days specifically--the tool creates TXT records in the appropriate Azure DNS zone but doesn't seem to be able to validate afterward. I've also been able to confirm that if a TXT record is already in place, it will be updated, but the challenge only sees an invalid string. 

I assume this is some kind of quirk regarding DNS propagation, but even when giving a 5 minute verification timer the order is still never verified. Any guidance would be appreciated.

**Comment by bjburke002** [comment]
Hi, just to follow up--after adding a short delay before moving into this.WaitForVerificationWithTable() in OrderCommand, certs are being provided as expected. Appears this is a quirk where LetsEncrypt only allows for one check and it happens to occur before DNS records can finish propagating.

**Comment by scabana** [comment]
Just got this error and I'm running the latest release, is this really fixed?
